(() => {
  'use strict';
  const startBtn=document.getElementById('startTripBtn'),pauseBtn=document.getElementById('pauseTripBtn'),finishBtn=document.getElementById('finishTripBtn'),elapsedEl=document.getElementById('elapsedTime');
  const recordingStatus=document.getElementById('recordingStatus'),recordingText=document.getElementById('recordingText'),altitudeEl=document.getElementById('altitude'),headingEl=document.getElementById('heading'),qualityEl=document.getElementById('gpsQuality');
  let timerId=null,lastAlertAt=0,lastNativeSyncAt=0,autoStatusTimer=null;
  function formatElapsed(ms){if(window.GPSSpeedUtils?.formatDuration)return window.GPSSpeedUtils.formatDuration(ms);const s=Math.max(0,Math.floor((+ms||0)/1000)),h=Math.floor(s/3600),m=Math.floor(s%3600/60),ss=s%60;return[h,m,ss].map(v=>String(v).padStart(2,'0')).join(':');}
  function formatHeading(value){const d=((+value%360)+360)%360;if(!Number.isFinite(d))return'--';const dirs=['N','NE','L','SE','S','SO','O','NO'];return `${dirs[Math.round(d/45)%8]} ${Math.round(d)}°`;}
  function updateTimer(){if(elapsedEl&&window.GPSSpeedTracking)elapsedEl.textContent=formatElapsed(window.GPSSpeedTracking.getElapsedMs());}
  function startTimer(){stopTimer();updateTimer();timerId=setInterval(updateTimer,1000);}function stopTimer(){if(timerId!==null){clearInterval(timerId);timerId=null;}}
  function setRecordingState(state){if(!recordingStatus||!recordingText)return;recordingStatus.classList.toggle('on',state==='running');recordingText.textContent=state==='running'?'GRAVANDO PERCURSO':state==='paused'?'PERCURSO PAUSADO':state==='finished'?'PERCURSO SALVO':'PRONTO PARA REGISTRAR';}
  function setButtons(state){if(!startBtn||!pauseBtn||!finishBtn)return;setRecordingState(state);if(state==='running'){startBtn.disabled=true;startBtn.textContent='Percurso em andamento';pauseBtn.disabled=false;pauseBtn.textContent='Pausar';finishBtn.disabled=false;return;}if(state==='paused'){startBtn.disabled=true;startBtn.textContent='Percurso pausado';pauseBtn.disabled=false;pauseBtn.textContent='Continuar';finishBtn.disabled=false;return;}startBtn.disabled=false;startBtn.textContent=state==='finished'?'Novo percurso':'Iniciar percurso';pauseBtn.disabled=true;pauseBtn.textContent='Pausar';finishBtn.disabled=true;}
  function resetForNewTrip(){window.GPSSpeedTracking?.reset();window.GPSSpeedometer?.reset();try{window.AndroidBridge?.clearTrackingSnapshot?.();}catch(_){}if(elapsedEl)elapsedEl.textContent='00:00:00';}
  function maybeSpeedAlert(speed){const settings=window.GPSSpeedSettings?.load?.();if(!settings?.speedAlertEnabled)return;const limit=+settings.speedAlertLimit||100,now=Date.now();if(speed>=limit&&now-lastAlertAt>15000){lastAlertAt=now;if('vibrate'in navigator)navigator.vibrate([200,100,200]);}}
  function updateGpsMetadata(p){if(!p)return;if(altitudeEl)altitudeEl.textContent=Number.isFinite(+p.altitude)?`${Math.round(+p.altitude)} m`:'--';if(headingEl)headingEl.textContent=formatHeading(p.heading);if(qualityEl){const used=+p.satellitesUsed||0,visible=+p.satellitesVisible||0,a=+p.accuracy;qualityEl.textContent=used>0?`${used}/${visible||used} sat`:Number.isFinite(a)?(a<=5?'Excelente':a<=12?'Boa':a<=25?'Média':'Fraca'):'--';}}
  function readNativeSnapshot(){try{if(!window.AndroidBridge?.getTrackingSnapshot)return null;const raw=window.AndroidBridge.getTrackingSnapshot();return typeof raw==='string'?JSON.parse(raw):raw;}catch(_){return null;}}
  function updateAutoWaitingStatus(){const localState=window.GPSSpeedTracking?.getState?.();if(localState&&['running','paused'].includes(localState.status))return;const s=readNativeSnapshot();if(!s?.autoEnabled)return;if(recordingStatus&&recordingText){const active=!!s.autoActive;recordingStatus.classList.toggle('on',active);recordingText.textContent=active?'GRAVANDO PERCURSO AUTOMÁTICO':`AUTOMÁTICO • ${Math.max(0,Math.min(100,+s.autoProgressMeters||0))}/100 m`;}
    if(qualityEl&&+s.satellitesUsed>0)qualityEl.textContent=`${+s.satellitesUsed}/${+s.satellitesVisible||+s.satellitesUsed} sat`;
  }
  function syncNativeSnapshot(force=false){if(!window.GPSSpeedTracking||!window.AndroidBridge?.getTrackingSnapshot)return false;const now=Date.now();if(!force&&now-lastNativeSyncAt<1200)return false;lastNativeSyncAt=now;try{const snapshot=readNativeSnapshot();if(!snapshot||!['running','paused'].includes(snapshot.status)){updateAutoWaitingStatus();return false;}const restored=window.GPSSpeedTracking.restoreFromSnapshot(snapshot);if(!restored)return false;const points=Array.isArray(snapshot.points)?snapshot.points:[];window.GPSSpeedometer?.reset?.();points.forEach(p=>window.GPSSpeedometer?.updateSpeed?.(+p.speedKmh||0));const latest=snapshot.lastPoint||points.at(-1);if(latest){if(!latest.satellitesUsed&&snapshot.satellitesUsed){latest.satellitesUsed=snapshot.satellitesUsed;latest.satellitesVisible=snapshot.satellitesVisible;}window.GPSSpeedGPS?.ingestNativePoint?.(latest,{emit:false});updateGpsMetadata(latest);}setButtons(snapshot.status);if(snapshot.status==='running'){startTimer();window.GPSSpeedGPS?.start?.();}else{stopTimer();updateTimer();}return true;}catch(e){console.warn('Não foi possível sincronizar o rastreamento nativo:',e);return false;}}
  startBtn?.addEventListener('click',()=>{if(!window.GPSSpeedTracking)return;const current=window.GPSSpeedTracking.getState();if(current.status==='finished')resetForNewTrip();window.GPSSpeedTracking.start();try{window.AndroidBridge?.startTracking?.();}catch(_){}setButtons('running');startTimer();});
  pauseBtn?.addEventListener('click',()=>{if(!window.GPSSpeedTracking)return;const current=window.GPSSpeedTracking.getState();if(current.status==='running'){window.GPSSpeedTracking.pause();try{window.AndroidBridge?.pauseTracking?.();}catch(_){}setButtons('paused');stopTimer();updateTimer();return;}if(current.status==='paused'){window.GPSSpeedTracking.resume();try{window.AndroidBridge?.resumeTracking?.();}catch(_){}setButtons('running');startTimer();window.GPSSpeedGPS?.start?.();}});
  finishBtn?.addEventListener('click',()=>{if(!window.GPSSpeedTracking)return;syncNativeSnapshot(true);window.GPSSpeedTracking.finish();stopTimer();updateTimer();setButtons('finished');window.GPSSpeedGPS?.stop?.();try{window.AndroidBridge?.stopTracking?.();}catch(_){}try{const saved=window.GPSSpeedTrips?.saveCurrentTrip?.();if(saved){window.GPSSpeedTracking?.clearCheckpoint?.();try{window.AndroidBridge?.clearTrackingSnapshot?.();}catch(_){}window.dispatchEvent(new CustomEvent('gpsspeed:trip-ready-to-save',{detail:{trip:saved,speed:window.GPSSpeedometer?.getStats?.()||null}}));}}catch(e){console.error('Não foi possível salvar o percurso:',e);}});
  window.addEventListener('gpsspeed:gps-update',e=>updateGpsMetadata(e.detail));window.addEventListener('gpsspeed:speed-update',e=>maybeSpeedAlert(+e.detail?.currentSpeed||0));window.addEventListener('gpsspeed:tracking-start',()=>setButtons('running'));window.addEventListener('gpsspeed:tracking-pause',()=>setButtons('paused'));window.addEventListener('gpsspeed:tracking-resume',()=>setButtons('running'));window.addEventListener('gpsspeed:tracking-finish',()=>setButtons('finished'));window.addEventListener('gpsspeed:kilometer-complete',e=>{if(e.detail?.split&&'vibrate'in navigator)navigator.vibrate(60);});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')syncNativeSnapshot(true);});window.addEventListener('focus',()=>syncNativeSnapshot());window.addEventListener('gpsspeed:native-resume',()=>setTimeout(()=>syncNativeSnapshot(true),150));
  const restored=window.GPSSpeedTracking?.restoreCheckpoint?.()||false;if(restored){const s=window.GPSSpeedTracking.getState().status;setButtons(s);if(s==='running')startTimer();}else setButtons(window.GPSSpeedTracking?.getState?.().status||'idle');updateTimer();setTimeout(()=>syncNativeSnapshot(true),400);autoStatusTimer=setInterval(updateAutoWaitingStatus,3000);
})();